/**
 * Fitbod exercise name -> Hevy built-in exercise name.
 * Names that are not listed pass through unchanged; Hevy then creates a custom exercise on import.
 */
export const EXERCISE_MAPPINGS: ReadonlyMap<string, string> = new Map<string, string>([
    ["Single Leg Kickback", "Glute Kickback on Floor"],
    ["Single Arm Dumbbell Tricep Extension", "Single Arm Tricep Extension (Dumbbell)"],
    ["Seated Tricep Press", "Seated Triceps Press"],
    ["Reverse Dumbbell Curl", "Reverse Curl (Dumbbell)"],
    ["Scissor Kick", "Ab Scissors"],
    ["Pike Push Up", "Pike Pushup"],
    ["Leg Raise", "Lying Leg Raise"],
    ["Incline Dumbbell Row", "Chest Supported Incline Row (Dumbbell)"],
    ["Incline Dumbbell Curl", "Seated Incline Curl (Dumbbell)"],
    ["Elevated Hip Bridge", "Hip Thrust (Bodyweight)"],
    ["Jackknife Sit-Up", "Jackknife Sit Up"],
    ["Hammer Curls", "Hammer Curl (Dumbbell)"],
    ["Dumbbell Squat", "Squat (Dumbbell)"],
    ["Dumbbell Shoulder Raise", "Lateral Raise (Dumbbell)"],
    ["Dumbbell Rear Delt Raise", "Rear Delt Reverse Fly (Dumbbell)"],
    // Hevy has no dumbbell hip thrust; merged into the barbell exercise on purpose.
    ["Dumbbell Hip Thrust", "Hip Thrust (Barbell)"],
    ["Dumbbell Goblet Squat", "Goblet Squat"],
    ["Dumbbell Front Raise", "Front Raise (Dumbbell)"],
    ["Dumbbell Fly", "Chest Fly (Dumbbell)"],
    ["Dumbbell Bent Over Reverse Fly", "Rear Delt Reverse Fly (Dumbbell)"],
    ["Bodyweight Bulgarian Split Squat", "Bulgarian Split Squat"],
    ["Vertical Leg Raise", "Leg Raise Parallel Bars"],
    ["Single Leg Leg Extension", "Single Leg Extensions"],
    ["Air Squats", "Squat (Bodyweight)"],
    ["Dumbbell Bent Over Row", "Bent Over Row (Dumbbell)"],
    ["Decline Sit Up", "Decline Crunch"],
    ["Dumbbell Bulgarian Split Squat", "Bulgarian Split Squat"],
    ["Dip", "Triceps Dip"],
    ["Lying Hamstrings Curl", "Lying Leg Curl (Machine)"],
    ["Barbell Incline Bench Press", "Incline Bench Press (Barbell)"],
    ["Dumbbell Incline Bench Press", "Incline Bench Press (Dumbbell)"],
    ["Smith Machine Incline Bench Press", "Incline Bench Press (Smith Machine)"],
    ["Smith Machine Bench Press", "Bench Press (Smith Machine)"],
    ["Dumbbell Bench Press", "Bench Press (Dumbbell)"],
    ["Barbell Bench Press", "Bench Press (Barbell)"],
    ["Machine Bench Press", "Chest Press (Machine)"],
    ["Dumbbell Pullover", "Pullover (Dumbbell)"],
    ["Dumbbell Decline Bench Press", "Decline Bench Press (Dumbbell)"],
    ["Barbell Decline Bench Press", "Decline Bench Press (Barbell)"],
    ["Standing Arnold Press", "Arnold Press (Dumbbell)"],
    ["Arnold Dumbbell Press", "Arnold Press (Dumbbell)"],
    ["Standing Dumbbell Shoulder Press", "Overhead Press (Dumbbell)"],
    ["Dumbbell Shoulder Press", "Shoulder Press (Dumbbell)"],
    ["Seated Barbell Shoulder Press", "Seated Overhead Press (Barbell)"],
    ["Machine Shoulder Press", "Seated Shoulder Press (Machine)"],
    ["Barbell Shoulder Press", "Overhead Press (Barbell)"],
    ["Smith Machine Overhead Shoulder Press", "Overhead Press (Smith Machine)"],
    ["Dumbbell Skullcrusher", "Skullcrusher (Dumbbell)"],
    ["EZ-Bar Skullcrusher", "Skullcrusher (Barbell)"],
    ["Skullcrusher", "Skullcrusher (Dumbbell)"],
    ["Lat Pulldown", "Lat Pulldown (Cable)"],
    ["Machine Fly", "Chest Fly (Machine)"],
    ["Mid Cable Crossover Fly", "Cable Fly Crossovers"],
    ["Machine Rear Delt Fly", "Rear Delt Reverse Fly (Machine)"],
    ["Machine Leg Press", "Leg Press (Machine)"],
    ["Back Squat", "Squat (Barbell)"],
    ["Pause Back Squat", "Pause Squat (Barbell)"],
    ["Dumbbell Sumo Squat", "Sumo Squat (Dumbbell)"],
    ["Kettlebell Sumo Squat", "Sumo Squat (Kettlebell)"],
    ["Leg Extension", "Leg Extension (Machine)"],
    ["Seated Leg Curl", "Seated Leg Curl (Machine)"],
    ["Leg Curl", "Lying Leg Curl (Machine)"],
    ["Machine Hip Abductor", "Hip Abduction (Machine)"],
    ["Machine Tigh Abductor", "Hip Abduction (Machine)"],
    ["Machine Hip Adductor", "Hip Adduction (Machine)"],
    ["Calf Press", "Calf Press (Machine)"],
    ["Seated Machine Calf Press", "Calf Press (Machine)"],
    ["Standing Calf Press", "Calf Press (Machine)"],
    ["Dumbbell Lunge", "Lunge (Dumbbell)"],
    ["Barbell Lunge", "Lunge (Barbell)"],
    ["Side Lunge", "Lateral Lunge"],
    ["EZ-Bar Curl", "EZ Bar Biceps Curl"],
    ["Close-Grip EZ-Bar Curl", "EZ Bar Biceps Curl"],
    ["Cable Rope Tricep Extension", "Triceps Rope Pushdown"],
    ["Cable Tricep Extension", "Triceps Rope Pushdown"],
    ["Triceps Pressdown", "Triceps Pushdown"],
    ["Bent Over Barbell Row", "Bent Over Row (Barbell)"],
    ["Cable Row", "Seated Cable Row - Bar Grip"],
    ["Cable Row with Squat", "Squat Row"],
    ["Cable Upright Row", "Upright Row (Cable)"],
    ["T-Bar Row", "T Bar Row"],
    ["Machine Row", "Seated Row (Machine)"],
    ["Straight-Arm Pulldown", "Rope Straight Arm Pulldown"],
    ["Hammerstrength Iso Row", "Iso-Lateral Row (Machine)"],
    ["Dumbbell Shrug", "Shrug (Dumbbell)"],
    ["Barbell Shrug", "Shrug (Barbell)"],
    ["Cable Shrug", "Shrug (Cable)"],
    ["Lateral Raise", "Lateral Raise (Dumbbell)"],
    ["Side Lateral Raise", "Lateral Raise (Dumbbell)"],
    ["Cable Lateral Raise", "Lateral Raise (Cable)"],
    ["Machine Lateral Raise", "Lateral Raise (Machine)"],
    ["Smith Machine Shrug", "Shrug (Smith Machine)"],
    ["Smith Machine Behind the Back Shrug Shrug", "Shrug (Smith Machine)"],
    ["Deadlift", "Deadlift (Barbell)"],
    ["Romanian Deadlift", "Romanian Deadlift (Barbell)"],
    ["Dumbbell Romanian Deadlift", "Romanian Deadlift (Dumbbell)"],
    ["Low Cable Chest Fly", "Low Cable Fly Crossovers"],
    ["Cable Crossover Fly", "Cable Fly Crossovers"],
    ["Dumbbell Incline Fly", "Incline Chest Fly (Dumbbell)"],
    ["Dumbbell Bicep Curl", "Bicep Curl (Dumbbell)"],
    ["Cable Bicep Curl", "Bicep Curl (Cable)"],
    ["Barbell Curl", "Bicep Curl (Barbell)"],
    ["Dumbbell Preacher Curl", "Preacher Curl (Dumbbell)"],
    ["Preacher Curl", "Preacher Curl (Barbell)"],
    ["Machine Preacher Curl", "Preacher Curl (Machine)"],
    ["Crunches", "Crunch"],
]);
